version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: chemist_db
    environment:
      MYSQL_ROOT_PASSWORD: '@12345Admin'
      MYSQL_DATABASE: 'chemist_db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '@12345Admin'
    ports:
      - "3307:3306"
    volumes:
      - chemist_mysql_vol:/var/lib/mysql
    networks:
      - chemist_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  chemist-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    image: chemist-backend-img:latest
    container_name: chemist_backend
    volumes:
      - ./backend:/app
      - chemist_backend_node_modules:/app/node_modules
    networks:
      - chemist_network
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    depends_on:
      mysql:
        condition: service_healthy
    command: sh -c "
      npx prisma generate &&
      npx prisma migrate deploy &&
      npm run prisma:seed &&
      npm run start:dev"
    restart: always
    environment:
      - DB_HOST=mysql

  chemist-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    image: chemist-frontend-img:latest
    container_name: chemist_frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - chemist-backend
    volumes:
      - ./frontend:/app
      - chemist_frontend_node_modules:/app/node_modules
      - chemist_frontend_vol:/app/.next
    networks:
      - chemist_network
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
    command: sh -c "npm run start:dev"
    restart: always

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: chemist_pma
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: admin
      PMA_PASSWORD: '@12345Admin'
      MYSQL_ROOT_PASSWORD: '@12345Admin'
      PMA_ARBITRARY: 1
      UPLOAD_LIMIT: 700M
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - chemist_network
    restart: always

volumes:
  chemist_mysql_vol:
    name: chemist_mysql_vol
  chemist_backend_node_modules:
    name: chemist_backend_node_modules
  chemist_frontend_node_modules:
    name: chemist_frontend_node_modules
  chemist_frontend_vol:
    name: chemist_frontend_vol

networks:
  chemist_network:
    driver: bridge